from deepface import DeepFace

class Img_Comparssion():
    #should client have oath token generated by defaulted false?
    #where does the token get gernated also?
    #genrated the class for now 
    def __init__(self, img1, img2, oauth):
        self.img1 = img1
        self.img2 = img2
        self.oauth = oauth